version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/src
      - node-modules:/src/blog/node_modules
    tty: true

volumes:
  node-modules:
